spring:
  redis:
    host: 192.168.31.21
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    client-type: lettuce # 客户端
  servlet:
    multipart:
      max-file-size: 100 # 最大文件100M
      max-request-size: 100 # 最大请求100M
server:
  port: 8080

# 自定义
redis:
  lock:
    sleep-time: 10
    time-out: 5
